{
 "title": "Resonate",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "percentile",
    "query": "p50 : 0.50, p90 : 0.90, p99 : 0.99"
   }
  ]
 },
 "panels": [
  { "title": "Promises", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(promises_total{state=\"created\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resolved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(promises_total{state=\"resolved\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(promises_total{state=\"rejected\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timedout",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(promises_total{state=\"timedout\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tasks_total{state=\"created\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tasks_total{state=\"dropped\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tasks_total{state=\"completed\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timedout",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tasks_total{state=\"timedout\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(api_requests_total{status!~\"2.*\"}[$__rate_interval])) / sum(rate(api_requests_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (type, protocol, status) (rate(api_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(api_duration_seconds_bucket[$__range])) by (le, type, protocol))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Submissions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(aio_submissions_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submission Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_submissions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(aio_submissions_total{status=\"failure\"}[$__rate_interval])) / sum(rate(aio_submissions_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(aio_connection[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submissions",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (type, status) (rate(aio_submissions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submission Duration",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(aio_duration_seconds_bucket[$__range])) by (le, type))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coroutines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(coroutines_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum by (type) (rate(coroutines_total[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(coroutines_seconds_bucket[$__range])) by (le, type))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "filters": [
      { "id": "c9328663", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "resonate" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"resonate\"}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  }
 ]
}